name: "my_new_project" # Replace with your actual project name
version: "1.0.0"
config-version: 2

profile: "my_new_project" # Should match the profile name in profiles.yml

# Define where dbt should look for models and configurations.
# Set to the top-level models folder, not specific subfolders.
source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

# Define the default materialization and configurations for each folder in the project
models:
  my_new_project: # Replace with your project name
    # Set default configs for the entire project
    +materialized: view
    +schema: "analytics"

    staging:
      +schema: "staging" # Separate schema for staging
      +materialized: view # Typically use views for staging models

    datamart:
      +schema: "datamart" # Separate schema for datamart models
      +materialized: table # Materialize dim and fact tables as tables
      
# Define tests and configurations for all seed files (if any) in the project
seeds:
  my_new_project:
    +schema: "raw_data"
    +quote_columns: true

# Add macros directory if any custom macros are used in this project
macro-paths: ["macros"]

# Set up variables that might be used in the project
vars:
  date_cutoff: "2023-01-01" # Example of a variable that could be used in models for filtering
  environment: "dev" # Can be used to dynamically adjust configs based on environment

# Configurations for snapshots (if used)
snapshots:
  my_new_project:
    +schema: "snapshots"
